<?xml version="1.0" encoding="UTF-8" ?>

<!--									-->
<!-- ISO-3166-2 Standard for country subdivisions			-->
<!--									-->
<!-- The following conventions are used in this file:			-->
<!--									-->
<!-- If the standard lists a subdivision name in more than language	-->
<!-- and/or romanization system, only the first listed name is shown.	-->
<!--									-->
<!-- Proper subdivision codes have the format 'XX-YYY' where XX is the	-->
<!-- ISO 3166-1 Alpha-2 country code and YYY is a 1-, 2- or 3-character	-->
<!-- code  for the subdivision.						-->
<!--									-->
<!-- For some countries the standard also lists a second level of	-->
<!-- regional divisions (e.g. for BE, FR, GB, IT, etc.). The codes	-->
<!-- for these regional divisions are shown as 'XX YYYY', i.e. with a	-->
<!-- space character instead of the '-'.				-->
<!--									-->
<!-- The sorting order is the same that is used in the standard.	-->
<!--									-->
<!-- Up-to-date as of newsletter, 2004-03-08, Newsletter 2.		-->
<!--									-->
<!-- Up-to-date as of what?!:  Google says:				-->
<!-- ``ISO 3166-2 Newsletter Number I-6 was published on 2004-03-08.''	-->
<!-- (http://google.com/search?q=iso%203166%20newsletter%202004-03-08)	-->
<!-- Cf. http://en.wikipedia.org/wiki/ISO_3166-2                        -->
<!--  -Jan Minář							-->

<!DOCTYPE iso_3166_2_entries [
	<!ELEMENT iso_3166_2_entries (iso_3166_country+)>
	<!ELEMENT iso_3166_country (
		iso_3166_subset*	|
		geographical_region*	|
		iso_3166_2_entry*
	)>
	<!ATTLIST iso_3166_country
		code			CDATA	#REQUIRED
	>
	<!ELEMENT iso_3166_subset (iso_3166_2_entry+)>
	<!ATTLIST iso_3166_subset
		type			CDATA	#IMPLIED
	>
	<!ELEMENT geographical_region (region+)>
	<!ATTLIST geographical_region
		type			CDATA	#IMPLIED
	>
	<!ELEMENT iso_3166_2_entry EMPTY>
	<!ATTLIST iso_3166_2_entry
		code			CDATA	#REQUIRED
		name			CDATA	#REQUIRED
	>
	<!ELEMENT region EMPTY>
	<!ATTLIST region
		code			CDATA	#REQUIRED
		name			CDATA	#REQUIRED
		comment			CDATA	#IMPLIED
	>
]>

<iso_3166_2_entries>
	<!-- United Arab Emirates -->
<iso_3166_country code="AE">
	<iso_3166_2_entry
		code="AE-AZ"  name="Abu Zaby" />
	<iso_3166_2_entry
		code="AE-AJ" 	name="'Ajman" />
	<iso_3166_2_entry
		code="AE-FU"	name="Al Fujayrah" />
	<iso_3166_2_entry
		code="AE-SH"	name="Ash Shariqah" />
	<iso_3166_2_entry
		code="AE-DU"	name="Dubayy" />
	<iso_3166_2_entry
		code="AE-RK"	name="Ra's al Khaymah" />
	<iso_3166_2_entry
		code="AE-UQ"	name="Umm al Qaywayn" />
</iso_3166_country>
	<!-- Afghanistan -->
<iso_3166_country code="AF">
	<iso_3166_2_entry
		code="AF-BDS"	name="Badakhshan" />
	<iso_3166_2_entry
		code="AF-BDG"	name="Badghis" />
	<iso_3166_2_entry
		code="AF-BGL"	name="Baghlan" />
	<iso_3166_2_entry
		code="AF-BAL"	name="Balkh" />
	<iso_3166_2_entry
		code="AF-BAM"	name="Bamian" />
	<iso_3166_2_entry
		code="AF-DAY"   name="Daykondi" />
        <iso_3166_2_entry
		code="AF-FRA"	name="Farah" />
	<iso_3166_2_entry
		code="AF-FYB"	name="Faryab" />
	<iso_3166_2_entry
		code="AF-GHA"	name="Ghazni" />
	<iso_3166_2_entry
		code="AF-GHO"	name="Ghowr" />
	<iso_3166_2_entry
		code="AF-HEL"	name="Helmand" />
	<iso_3166_2_entry
		code="AF-HER"	name="Herat" />
	<iso_3166_2_entry
		code="AF-JOW"	name="Jowzjan" />
	<iso_3166_2_entry
		code="AF-KAB"	name="Kabul" />
	<iso_3166_2_entry
		code="AF-KAN"	name="Kandahar" />
	<iso_3166_2_entry
		code="AF-KAP"	name="Kapisa" />
	<iso_3166_2_entry
		code="AF-KHO"	name="Khowst" />
	<iso_3166_2_entry
		code="AF-KNR"	name="Konar" />
	<iso_3166_2_entry
		code="AF-KDZ"	name="Kondoz" />
	<iso_3166_2_entry
		code="AF-LAG"	name="Laghman" />
	<iso_3166_2_entry
		code="AF-LOW"	name="Lowgar" />
	<iso_3166_2_entry
		code="AF-NAN"	name="Nangrahar" />
	<iso_3166_2_entry
		code="AF-NIM"	name="Nimruz" />
	<iso_3166_2_entry
		code="AF-NUR"	name="Nurestan" />
	<iso_3166_2_entry
		code="AF-ORU"	name="Oruzgan" />
	<iso_3166_2_entry
		code="AF-PIA"	name="Paktia" />
	<iso_3166_2_entry
		code="AF-PKA"	name="Paktika" />
	<iso_3166_2_entry
		code="AF-PAN"   name="Panjshir" />
        <iso_3166_2_entry
		code="AF-PAR"	name="Parwan" />
	<iso_3166_2_entry
		code="AF-SAM"	name="Samangan" />
	<iso_3166_2_entry
		code="AF-SAR"	name="Sar-e Pol" />
	<iso_3166_2_entry
		code="AF-TAK"	name="Takhar" />
	<iso_3166_2_entry
		code="AF-WAR"	name="Wardak" />
	<iso_3166_2_entry
		code="AF-ZAB"	name="Zabol" />
</iso_3166_country>
	<!-- Albania -->
<iso_3166_country code="AL">
	<iso_3166_2_entry
		code="AL-BR"	name="Berat" />
	<iso_3166_2_entry
		code="AL-BU"	name="Bulqizë" />
	<iso_3166_2_entry
		code="AL-DL"	name="Delvinë" />
	<iso_3166_2_entry
		code="AL-DV"	name="Devoll" />
	<iso_3166_2_entry
		code="AL-DI"	name="Dibër" />
	<iso_3166_2_entry
		code="AL-DR"	name="Durrës" />
	<iso_3166_2_entry
		code="AL-EL"	name="Elbasan" />
	<iso_3166_2_entry
		code="AL-FR"	name="Fier" />
	<iso_3166_2_entry
		code="AL-GR"	name="Gramsh" />
	<iso_3166_2_entry
		code="AL-GJ"	name="Gjirokastër" />
	<iso_3166_2_entry
		code="AL-HA"	name="Has" />
	<iso_3166_2_entry
		code="AL-KA"	name="Kavajë" />
	<iso_3166_2_entry
		code="AL-ER"	name="Kolonjë" />
	<iso_3166_2_entry
		code="AL-KO"	name="Korcë" />
	<iso_3166_2_entry
		code="AL-KR"	name="Krujë" />
	<iso_3166_2_entry
		code="AL-KC"	name="Kuçovë" />
	<iso_3166_2_entry
		code="AL-KU"	name="Kukës" />
	<iso_3166_2_entry
		code="AL-KB"	name="Kurbin" />
	<iso_3166_2_entry
		code="AL-LE"	name="Lezhë" />
	<iso_3166_2_entry
		code="AL-LB"	name="Librazhd" />
	<iso_3166_2_entry
		code="AL-LU"	name="Lushnjë" />
	<iso_3166_2_entry
		code="AL-MM"	name="Malësi e Madhe" />
	<iso_3166_2_entry
		code="AL-MK"	name="Mallakastër" />
	<iso_3166_2_entry
		code="AL-MT"	name="Mat" />
	<iso_3166_2_entry
		code="AL-MR"	name="Mirditë" />
	<iso_3166_2_entry
		code="AL-PQ"	name="Peqin" />
	<iso_3166_2_entry
		code="AL-PR"	name="Përmet" />
	<iso_3166_2_entry
		code="AL-PG"	name="Pogradec" />
	<iso_3166_2_entry
		code="AL-PU"	name="Pukë" />
	<iso_3166_2_entry
		code="AL-SR"	name="Sarandë" />
	<iso_3166_2_entry
		code="AL-SK"	name="Skrapar" />
	<iso_3166_2_entry
		code="AL-SH"	name="Shkodër" />
	<iso_3166_2_entry
		code="AL-TE"	name="Tepelenë" />
	<iso_3166_2_entry
		code="AL-TR"	name="Tiranë" />
	<iso_3166_2_entry
		code="AL-TP"	name="Tropojë" />
	<iso_3166_2_entry
		code="AL-VL"	name="Vlorë" />
</iso_3166_country>
	<!-- Armenia -->
<iso_3166_country code="AM">
	<iso_3166_2_entry
		code="AM-ER"	name="Erevan" />
	<iso_3166_2_entry
		code="AM-AG"	name="Aragacotn" />
	<iso_3166_2_entry
		code="AM-AR"	name="Ararat" />
	<iso_3166_2_entry
		code="AM-AV"	name="Armavir" />
	<iso_3166_2_entry
		code="AM-GR"	name="Gegarkunik'" />
	<iso_3166_2_entry
		code="AM-KT"	name="Kotayk'" />
	<iso_3166_2_entry
		code="AM-LO"	name="Lory" />
	<iso_3166_2_entry
		code="AM-SH"	name="Sirak" />
	<iso_3166_2_entry
		code="AM-SU"	name="Syunik'" />
	<iso_3166_2_entry
		code="AM-TV"	name="Tavus" />
	<iso_3166_2_entry
		code="AM-VD"	name="Vayoc Jor" />
</iso_3166_country>
	<!-- Angola -->
<iso_3166_country code="AO">
	<iso_3166_2_entry
		code="AO-BGO"	name="Bengo" />
	<iso_3166_2_entry
		code="AO-BGU"	name="Benguela" />
	<iso_3166_2_entry
		code="AO-BIE"	name="Bie" />
	<iso_3166_2_entry
		code="AO-CAB"	name="Cabinda" />
	<iso_3166_2_entry
		code="AO-CCU"	name="Cuando-Cubango" />
	<iso_3166_2_entry
		code="AO-CNO"	name="Cuanza Norte" />
		<iso_3166_2_entry
		code="AO-CUS"	name="Cuanza Sul" />
	<iso_3166_2_entry
		code="AO-CNN"	name="Cunene" />
	<iso_3166_2_entry
		code="AO-HUA"	name="Huambo" />
	<iso_3166_2_entry
		code="AO-HUI"	name="Huila" />
	<iso_3166_2_entry
		code="AO-LUA"	name="Luanda" />
	<iso_3166_2_entry
		code="AO-LNO"	name="Lunda Norte" />
	<iso_3166_2_entry
		code="AO-LSU"	name="Lunda Sul" />
	<iso_3166_2_entry
		code="AO-MAL"	name="Malange" />
	<iso_3166_2_entry
		code="AO-MOX"	name="Moxico" />
	<iso_3166_2_entry
		code="AO-NAM"	name="Namibe" />
	<iso_3166_2_entry
		code="AO-UIG"	name="Uige" />
	<iso_3166_2_entry
		code="AO-ZAI"	name="Zaire" />
</iso_3166_country>
<iso_3166_country code="AR">
	<!-- Argentina -->
	<iso_3166_2_entry
		code="AR-C"	name="Capital federal" />
	<iso_3166_2_entry
		code="AR-B"	name="Buenos Aires" />
	<iso_3166_2_entry
		code="AR-K"	name="Catamarca" />
	<iso_3166_2_entry
		code="AR-X"	name="Cordoba" />
	<iso_3166_2_entry
		code="AR-W"	name="Corrientes" />
	<iso_3166_2_entry
		code="AR-H"	name="Chaco" />
	<iso_3166_2_entry
		code="AR-U"	name="Chubut" />
	<iso_3166_2_entry
		code="AR-E"	name="Entre Rios" />
	<iso_3166_2_entry
		code="AR-P"	name="Formosa" />
	<iso_3166_2_entry
		code="AR-Y"	name="Jujuy" />
	<iso_3166_2_entry
		code="AR-L"	name="La Pampa" />
	<iso_3166_2_entry
		code="AR-M"	name="Mendoza" />
	<iso_3166_2_entry
		code="AR-N"	name="Misiones" />
	<iso_3166_2_entry
		code="AR-Q"	name="Neuquen" />
	<iso_3166_2_entry
		code="AR-R"	name="Rio Negro" />
	<iso_3166_2_entry
		code="AR-A"	name="Salta" />
	<iso_3166_2_entry
		code="AR-J"	name="San Juan" />
	<iso_3166_2_entry
		code="AR-D"	name="San Luis" />
	<iso_3166_2_entry
		code="AR-Z"	name="Santa Cruz" />
	<iso_3166_2_entry
		code="AR-S"	name="Santa Fe" />
	<iso_3166_2_entry
		code="AR-G"	name="Santiago del Estero" />
	<iso_3166_2_entry
		code="AR-V"	name="Tierra del Fuego" />
	<iso_3166_2_entry
		code="AR-T"	name="Tucuman" />
</iso_3166_country>
	<!-- Austria -->
<iso_3166_country code="AT">
	<iso_3166_2_entry
	code="AT-1" name="Burgenland" />
	<iso_3166_2_entry
	code="AT-2"	name="Kärnten" />
	<iso_3166_2_entry
	code="AT-3"	name="Niederosterreich" />
	<iso_3166_2_entry
	code="AT-4"	name="Oberosterreich" />
	<iso_3166_2_entry
	code="AT-5"	name="Salzburg" />
	<iso_3166_2_entry
	code="AT-6"	name="Steiermark" />
	<iso_3166_2_entry
	code="AT-7"	name="Tirol" />
	<iso_3166_2_entry
	code="AT-8"	name="Vorarlberg" />
	<iso_3166_2_entry
	code="AT-9"	name="Wien" />
</iso_3166_country>
	<!-- Australia -->
<iso_3166_country code="AU">
	<iso_3166_2_entry
		code="AU-AAT"	name="Australian Antarctic Territory" />
	<iso_3166_2_entry
		code="AU-ACT"	name="Australian Capital Territory" />
	<iso_3166_2_entry
		code="AU-NT"	name="Northern Territory" />
	<iso_3166_2_entry
		code="AU-NSW"	name="New South Wales" />
	<iso_3166_2_entry
		code="AU-QLD"	name="Queensland" />
	<iso_3166_2_entry
		code="AU-SA"	name="South Australia" />
	<iso_3166_2_entry
		code="AU-TAS"	name="Tasmania" />
	<iso_3166_2_entry
		code="AU-VIC"	name="Victoria" />
	<iso_3166_2_entry
		code="AU-WA"	name="Western Australia" />
</iso_3166_country>
	<!-- Azerbaijan -->
<iso_3166_country code="AZ">
	<iso_3166_2_entry
		code="AZ-NX"	name="Naxcivan" />
	<iso_3166_2_entry
		code="AZ-AB"	name="Ali Bayramli" />
	<iso_3166_2_entry
		code="AZ-BA"	name="Baki" />
	<iso_3166_2_entry
		code="AZ-GA"	name="Ganca" />
	<iso_3166_2_entry
		code="AZ-LA"	name="Lankaran" />
	<iso_3166_2_entry
		code="AZ-MI"	name="Mingacevir" />
	<iso_3166_2_entry
		code="AZ-NA"	name="Naftalan" />
	<iso_3166_2_entry
		code="AZ-SA"	name="Saki" />
	<iso_3166_2_entry
		code="AZ-SM"	name="Sumqayit" />
	<iso_3166_2_entry
		code="AZ-SS"	name="Susa" />
	<iso_3166_2_entry
		code="AZ-XA"	name="Xankandi" />
	<iso_3166_2_entry
		code="AZ-YE"	name="Yevlax" />
	<iso_3166_2_entry
		code="AZ-ABS"	name="Abseron" />
	<iso_3166_2_entry
		code="AZ-AGC"	name="Agcabadi" />
	<iso_3166_2_entry
		code="AZ-AGM"	name="Agdam" />
	<iso_3166_2_entry
		code="AZ-AGS"	name="Agdas" />
	<iso_3166_2_entry
		code="AZ-AGA"	name="Agstafa" />
	<iso_3166_2_entry
		code="AZ-AGU"	name="Agsu" />
	<iso_3166_2_entry
		code="AZ-AST"	name="Astara" />
	<iso_3166_2_entry
		code="AZ-BAB"	name="Babak" />
	<iso_3166_2_entry
		code="AZ-BAL"	name="Balakan" />
	<iso_3166_2_entry
		code="AZ-BAR"	name="Barda" />
	<iso_3166_2_entry
		code="AZ-BEY"	name="Beylagan" />
	<iso_3166_2_entry
		code="AZ-BIL"	name="Bilasuvar" />
	<iso_3166_2_entry
		code="AZ-CAB"	name="Cabrayll" />
	<iso_3166_2_entry
		code="AZ-CAL"	name="Calilabad" />
	<iso_3166_2_entry
		code="AZ-CUL"	name="Culfa" />
	<iso_3166_2_entry
		code="AZ-DAS"	name="Daskasan" />
	<iso_3166_2_entry
		code="AZ-DAV"	name="Davaci" />
	<iso_3166_2_entry
		code="AZ-FUZ"	name="Fuzuli" />
	<iso_3166_2_entry
		code="AZ-GAD"	name="Gadabay" />
	<iso_3166_2_entry
		code="AZ-GOR"	name="Goranboy" />
	<iso_3166_2_entry
		code="AZ-GOY"	name="Goycay" />
	<iso_3166_2_entry
		code="AZ-HAC"	name="Haciqabul" />
	<iso_3166_2_entry
		code="AZ-IMI"	name="Imisli" />
	<iso_3166_2_entry
		code="AZ-ISM"	name="Ismayilli" />
	<iso_3166_2_entry
		code="AZ-KAL"	name="Kalbacar" />
	<iso_3166_2_entry
		code="AZ-KUR"	name="Kurdamir" />
	<iso_3166_2_entry
		code="AZ-LAC"	name="Lacin" />
	<iso_3166_2_entry
		code="AZ-LAN"	name="Lankaran" />
	<iso_3166_2_entry
		code="AZ-LER"	name="Lerik" />
	<iso_3166_2_entry
		code="AZ-MAS"	name="Masalli" />
	<iso_3166_2_entry
		code="AZ-NEF"	name="Neftcala" />
	<iso_3166_2_entry
		code="AZ-OGU"	name="Oguz" />
	<iso_3166_2_entry
		code="AZ-ORD"	name="Ordubad" />
	<iso_3166_2_entry
		code="AZ-QAB"	name="Qabala" />
	<iso_3166_2_entry
		code="AZ-QAX"	name="Qax" />
	<iso_3166_2_entry
		code="AZ-QAZ"	name="Qazax" />
	<iso_3166_2_entry
		code="AZ-QOB"	name="Qobustan" />
	<iso_3166_2_entry
		code="AZ-QBA"	name="Quba" />
	<iso_3166_2_entry
		code="AZ-QBI"	name="Qubadli" />
	<iso_3166_2_entry
		code="AZ-QUS"	name="Qusar" />
	<iso_3166_2_entry
		code="AZ-SAT"	name="Saatli" />
	<iso_3166_2_entry
		code="AZ-SAB"	name="Sabirabad" />
	<iso_3166_2_entry
		code="AZ-SAD"	name="Sadarak" />
	<iso_3166_2_entry
		code="AZ-SAH"	name="Sahbuz" />
	<iso_3166_2_entry
		code="AZ-SAK"	name="Saki" />
	<iso_3166_2_entry
		code="AZ-SAL"	name="Salyan" />
	<iso_3166_2_entry
		code="AZ-SMI"	name="Samaxi" />
	<iso_3166_2_entry
		code="AZ-SKR"	name="Samkir" />
	<iso_3166_2_entry
		code="AZ-SMX"	name="Samux" />
	<iso_3166_2_entry
		code="AZ-SAR"	name="Sarur" />
	<iso_3166_2_entry
		code="AZ-SIY"	name="Siyazan" />
	<iso_3166_2_entry
		code="AZ-SUS"	name="Susa" />
	<iso_3166_2_entry
		code="AZ-TAR"	name="Tartar" />
	<iso_3166_2_entry
		code="AZ-TOV"	name="Tovuz" />
	<iso_3166_2_entry
		code="AZ-UCA"	name="Ucar" />
	<iso_3166_2_entry
		code="AZ-XAC"	name="Xacmaz" />
	<iso_3166_2_entry
		code="AZ-XAN"	name="Xanlar" />
	<iso_3166_2_entry
		code="AZ-XIZ"	name="Xizi" />
	<iso_3166_2_entry
		code="AZ-XCI"	name="Xocali" />
	<iso_3166_2_entry
		code="AZ-XVD"	name="Xocavand" />
	<iso_3166_2_entry
		code="AZ-YAR"	name="Yardimli" />
	<iso_3166_2_entry
		code="AZ-YEV"	name="Yevlax" />
	<iso_3166_2_entry
		code="AZ-ZAN"	name="Zangilan" />
	<iso_3166_2_entry
		code="AZ-ZAQ"	name="Zaqatala" />
	<iso_3166_2_entry
		code="AZ-ZAR"	name="Zardab" />
</iso_3166_country>
	<!-- Bosnia-Herzegovina -->
<iso_3166_country code="BA">
	<iso_3166_2_entry
		code="BA-BIH"	name="Federacija Bosna i Hercegovina" />
	<iso_3166_2_entry
		code="BA-SRP"	name="Republika Srpska" />
</iso_3166_country>
	<!-- Bangladesh --> 
<iso_3166_country code="BD">
	<iso_3166_2_entry
		code="BD-05"	name="Bagerhat zila" />
	<iso_3166_2_entry
		code="BD-01"	name="Bandarban zila" />
	<iso_3166_2_entry
		code="BD-02"	name="Barguna zila" />
	<iso_3166_2_entry
		code="BD-06"	name="Barisal zila" />
	<iso_3166_2_entry
		code="BD-07"	name="Bhola zila" />
	<iso_3166_2_entry
		code="BD-03"	name="Bogra zila" />
	<iso_3166_2_entry
		code="BD-04"	name="Brahmanbaria zila" />
	<iso_3166_2_entry
		code="BD-09"	name="Chandpur zila" />
	<iso_3166_2_entry
		code="BD-10"	name="Chittagong zila" />
	<iso_3166_2_entry
		code="BD-12"	name="Chuadanga zila" />
	<iso_3166_2_entry
		code="BD-08"	name="Comilla zila" />
	<iso_3166_2_entry
		code="BD-11"	name="Cox's Bazar zila" />
	<iso_3166_2_entry
		code="BD-13"	name="Dhaka zila" />
	<iso_3166_2_entry
		code="BD-14"	name="Dinajpur zila" />
	<iso_3166_2_entry
		code="BD-15"	name="Faridpur zila" />
	<iso_3166_2_entry
		code="BD-16"	name="Feni zila" />
	<iso_3166_2_entry
		code="BD-19"	name="Gaibandha zila" />
	<iso_3166_2_entry
		code="BD-18"	name="Gazipur zila" />
	<iso_3166_2_entry
		code="BD-17"	name="Gopalganj zila" />
	<iso_3166_2_entry
		code="BD-20"	name="Habiganj zila" />
	<iso_3166_2_entry
		code="BD-24"	name="Jaipurhat zila" />
	<iso_3166_2_entry
		code="BD-21"	name="Jamalpur zila" />
	<iso_3166_2_entry
		code="BD-22"	name="Jessore zila" />
	<iso_3166_2_entry
		code="BD-25"	name="Jhalakati zila" />
	<iso_3166_2_entry
		code="BD-23"	name="Jhenaidah zila" />
	<iso_3166_2_entry
		code="BD-29"	name="Khagrachari zila" />
	<iso_3166_2_entry
		code="BD-27"	name="Khulna zila" />
	<iso_3166_2_entry
		code="BD-26"	name="Kishorganj zila" />
	<iso_3166_2_entry
		code="BD-28"	name="Kurigram zila" />
	<iso_3166_2_entry
		code="BD-30"	name="Kushtia zila" />
	<iso_3166_2_entry
		code="BD-31"	name="Lakshmipur zila" />
	<iso_3166_2_entry
		code="BD-32"	name="Lalmonirhat zila" />
	<iso_3166_2_entry
		code="BD-36"	name="Madaripur zila" />
	<iso_3166_2_entry
		code="BD-37"	name="Magura zila" />
	<iso_3166_2_entry
		code="BD-33"	name="Manikganj zila" />
	<iso_3166_2_entry
		code="BD-39"	name="Meherpur zila" />
	<iso_3166_2_entry
		code="BD-38"	name="Moulvibazar zila" />
	<iso_3166_2_entry
		code="BD-35"	name="Munshiganj zila" />
	<iso_3166_2_entry
		code="BD-34"	name="Mymensingh zila" />
	<iso_3166_2_entry
		code="BD-48"	name="Naogaon zila" />
	<iso_3166_2_entry
		code="BD-43"	name="Narail zila" />
	<iso_3166_2_entry
		code="BD-40"	name="Narayanganj zila" />
	<iso_3166_2_entry
		code="BD-42"	name="Narsingdi zila" />
	<iso_3166_2_entry
		code="BD-44"	name="Natore zila" />
	<iso_3166_2_entry
		code="BD-45"	name="Nawabganj zila" />
	<iso_3166_2_entry
		code="BD-41"	name="Netrakona zila" />
	<iso_3166_2_entry
		code="BD-46"	name="Nilphamari zila" />
	<iso_3166_2_entry
		code="BD-47"	name="Noakhali zila" />
	<iso_3166_2_entry
		code="BD-49"	name="Pabna zila" />
	<iso_3166_2_entry
		code="BD-52"	name="Panchagarh zila" />
	<iso_3166_2_entry
		code="BD-51"	name="Patuakhali zila" />
	<iso_3166_2_entry
		code="BD-50"	name="Pirojpur zila" />
	<iso_3166_2_entry
		code="BD-53"	name="Rajbari zila" />
	<iso_3166_2_entry
		code="BD-54"	name="Rajshahi zila" />
	<iso_3166_2_entry
		code="BD-56"	name="Rangamati zila" />
	<iso_3166_2_entry
		code="BD-55"	name="Rangpur zila" />
	<iso_3166_2_entry
		code="BD-58"	name="Satkhira zila" />
	<iso_3166_2_entry
		code="BD-62"	name="Shariatpur zila" />
	<iso_3166_2_entry
		code="BD-57"	name="Sherpur zila" />
	<iso_3166_2_entry
		code="BD-59"	name="Sirajganj zila" />
	<iso_3166_2_entry
		code="BD-61"	name="Sunamganj zila" />
	<iso_3166_2_entry
		code="BD-60"	name="Sylhet zila" />
	<iso_3166_2_entry
		code="BD-63"	name="Tangail zila" />
	<iso_3166_2_entry
		code="BD-64"	name="Thakurgaon zila" />
</iso_3166_country>
	<!-- Belgium -->
<iso_3166_country code="BE">
	<iso_3166_2_entry
		code="BE-VAN"	name="Antwerpen" />
	<iso_3166_2_entry
		code="BE-WBR"	name="Brabant Wallon" />
	<iso_3166_2_entry
		code="BE-WHT"	name="Hainaut" />
	<iso_3166_2_entry
		code="BE-WLG"	name="Liege" />
	<iso_3166_2_entry
		code="BE-VLI"	name="Limburg" />
	<iso_3166_2_entry
		code="BE-WLX"	name="Luxembourg" />
	<iso_3166_2_entry
		code="BE-WNA"	name="Namur" />
	<iso_3166_2_entry
		code="BE-VOV"	name="Oost-Vlaanderen" />
	<iso_3166_2_entry
		code="BE-VBR"	name="Vlaams-Brabant" />
	<iso_3166_2_entry
		code="BE-VWV"	name="West-Vlaanderen" />
</iso_3166_country>
	<!-- Burkina-Faso -->
<iso_3166_country code="BF">
	<iso_3166_2_entry
		code="BF-BAL"	name="Bale" />
	<iso_3166_2_entry
		code="BF-BAM"	name="Bam" />
	<iso_3166_2_entry
		code="BF-BAN"	name="Banwa" />
	<iso_3166_2_entry
		code="BF-BAZ"	name="Bazega" />
	<iso_3166_2_entry
		code="BF-BGR"	name="Bougouriba" />
	<iso_3166_2_entry
		code="BF-BLG"	name="Boulgou" />
	<iso_3166_2_entry
		code="BF-BLK"	name="Boulkiemde" />
	<iso_3166_2_entry
		code="BF-COM"	name="Comoe" />
	<iso_3166_2_entry
		code="BF-GAN"	name="Ganzourgou" />
	<iso_3166_2_entry
		code="BF-GNA"	name="Gnagna" />
	<iso_3166_2_entry
		code="BF-GOU"	name="Gourma" />
	<iso_3166_2_entry
		code="BF-HOU"	name="Houet" />
	<iso_3166_2_entry
		code="BF-IOB"	name="Ioba" />
	<iso_3166_2_entry
		code="BF-KAD"	name="Kadiogo" />
	<iso_3166_2_entry
		code="BF-KEN"	name="Kenedougou" />
	<iso_3166_2_entry
		code="BF-KMD"	name="Komondjari" />
	<iso_3166_2_entry
		code="BF-KMP"	name="Kompienga" />
	<iso_3166_2_entry
		code="BF-KOS"	name="Kossi" />
	<iso_3166_2_entry
		code="BF-KOP"	name="Koulpulogo" />
	<iso_3166_2_entry
		code="BF-KOT"	name="Kouritenga" />
	<iso_3166_2_entry
		code="BF-KOW"	name="Kourweogo" />
	<iso_3166_2_entry
		code="BF-LER"	name="Leraba" />
	<iso_3166_2_entry
		code="BF-LOR"	name="Loroum" />
	<iso_3166_2_entry
		code="BF-MOU"	name="Mouhoun" />
	<iso_3166_2_entry
		code="BF-NAO"	name="Nahouri" />
	<iso_3166_2_entry
		code="BF-NAM"	name="Namentenga" />
	<iso_3166_2_entry
		code="BF-NAY"	name="Nayala" />
	<iso_3166_2_entry
		code="BF-NOU"	name="Noumbiel" />
	<iso_3166_2_entry
		code="BF-OUB"	name="Oubritenga" />
	<iso_3166_2_entry
		code="BF-OUD"	name="Oudalan" />
	<iso_3166_2_entry
		code="BF-PAS"	name="Passore" />
	<iso_3166_2_entry
		code="BF-PON"	name="Poni" />
	<iso_3166_2_entry
		code="BF-SNG"	name="Sanguie" />
	<iso_3166_2_entry
		code="BF-SMT"	name="Sanmatenga" />
	<iso_3166_2_entry
		code="BF-SEN"	name="Seno" />
	<iso_3166_2_entry
		code="BF-SIS"	name="Siasili" />
	<iso_3166_2_entry
		code="BF-SOM"	name="Soum" />
	<iso_3166_2_entry
		code="BF-SOR"	name="Sourou" />
	<iso_3166_2_entry
		code="BF-TAP"	name="Tapoa" />
	<iso_3166_2_entry
		code="BF-TUI"	name="Tuy" />
	<iso_3166_2_entry
		code="BF-YAG"	name="Yagha" />
	<iso_3166_2_entry
		code="BF-YAT"	name="Yatenga" />
	<iso_3166_2_entry
		code="BF-ZIR"	name="Ziro" />
	<iso_3166_2_entry
		code="BF-ZON"	name="Zondoma" />
	<iso_3166_2_entry
		code="BF-ZOU"	name="Zoundweogo" />
</iso_3166_country>
	<!-- Bulgaria -->
<iso_3166_country code="BG">
	<iso_3166_2_entry
		code="BG-01"	name="Blagoevgrad" />
	<iso_3166_2_entry
		code="BG-02"	name="Burgas" />
	<iso_3166_2_entry
		code="BG-08"	name="Dobric" />
	<iso_3166_2_entry
		code="BG-07"	name="Gabrovo" />
	<iso_3166_2_entry
		code="BG-26"	name="Haskovo" />
	<iso_3166_2_entry
		code="BG-28"	name="Jambol" />
	<iso_3166_2_entry
		code="BG-09"	name="Kardzali" />
	<iso_3166_2_entry
		code="BG-10"	name="Kyustendil" />
	<iso_3166_2_entry
		code="BG-11"	name="Lovech" />
	<iso_3166_2_entry
		code="BG-12"	name="Montana" />
	<iso_3166_2_entry
		code="BG-13"	name="Pazardzik" />
	<iso_3166_2_entry
		code="BG-14"	name="Pernik" />
	<iso_3166_2_entry
		code="BG-15"	name="Pleven" />
	<iso_3166_2_entry
		code="BG-16"	name="Plovdiv" />
	<iso_3166_2_entry
		code="BG-17"	name="Razgrad" />
	<iso_3166_2_entry
		code="BG-18"	name="Ruse" />
	<iso_3166_2_entry
		code="BG-19"	name="Silistra" />
	<iso_3166_2_entry
		code="BG-20"	name="Sliven" />
	<iso_3166_2_entry
		code="BG-21"	name="Smoljan" />
	<iso_3166_2_entry
		code="BG-23"	name="Sofija" />
	<iso_3166_2_entry
		code="BG-24"	name="Stara Zagora" />
	<iso_3166_2_entry
		code="BG-27"	name="Sumen" />
	<iso_3166_2_entry
		code="BG-25"	name="Targoviste" />
	<iso_3166_2_entry
		code="BG-03"	name="Varna" />
	<iso_3166_2_entry
		code="BG-04"	name="Veliko Tarnovo" />
	<iso_3166_2_entry
		code="BG-05"	name="Vidin" />
	<iso_3166_2_entry
		code="BG-06"	name="Vraca" />
</iso_3166_country>
	<!-- Bahrain -->
<iso_3166_country code="BH">
	<iso_3166_2_entry
		code="BH-01"	name="Al Hadd" />
	<iso_3166_2_entry
		code="BH-03"	name="Al Manamah" />
	<iso_3166_2_entry
		code="BH-10"	name="Al Mintaqah al Gharbiyah" />
	<iso_3166_2_entry
		code="BH-07"	name="Al Mintagah al Wusta" />
	<iso_3166_2_entry
		code="BH-05"	name="Al Mintaqah ash Shamaliyah" />
	<iso_3166_2_entry
		code="BH-02"	name="Al Muharraq" />
	<iso_3166_2_entry
		code="BH-09"	name="Ar Rifa" />
	<iso_3166_2_entry
		code="BH-04"	name="Jidd Hafs" />
	<iso_3166_2_entry
		code="BH-12"	name="Madluat Jamad" />
	<iso_3166_2_entry
		code="BH-08"	name="Madluat Isa" />
	<iso_3166_2_entry
		code="BH-11"	name="Mintaqat Juzur tawar" />
	<iso_3166_2_entry
		code="BH-06"	name="Sitrah" />
</iso_3166_country>
	<!-- Burundi -->
<iso_3166_country code="BI">
	<iso_3166_2_entry
		code="BI-BB"	name="Bubanza" />
	<iso_3166_2_entry
		code="BI-BJ"	name="Bujumbura" />
	<iso_3166_2_entry
		code="BI-BR"	name="Bururi" />
	<iso_3166_2_entry
		code="BI-CA"	name="Cankuzo" />
	<iso_3166_2_entry
		code="BI-CI"	name="Cibitoke" />
	<iso_3166_2_entry
		code="BI-GI"	name="Gitega" />
	<iso_3166_2_entry
		code="BI-KR"	name="Karuzi" />
	<iso_3166_2_entry
		code="BI-KY"	name="Kayanza" />
	<iso_3166_2_entry
		code="BI-MA"	name="Makamba" />
	<iso_3166_2_entry
		code="BI-MU"	name="Muramvya" />
	<iso_3166_2_entry
		code="BI-MW"	name="Mwaro" />
	<iso_3166_2_entry
		code="BI-NG"	name="Ngozi" />
	<iso_3166_2_entry
		code="BI-RT"	name="Rutana" />
	<iso_3166_2_entry
		code="BI-RY"	name="Ruyigi" />
</iso_3166_country>
	<!-- Benin -->
<iso_3166_country code="BJ">
	<iso_3166_2_entry
		code="BJ-AL"	name="Alibori" />
	<iso_3166_2_entry
		code="BJ-AK"	name="Atakora" />
	<iso_3166_2_entry
		code="BJ-AQ"	name="Atlantique" />
	<iso_3166_2_entry
		code="BJ-BO"	name="Borgou" />
	<iso_3166_2_entry
		code="BJ-CO"	name="Collines" />
	<iso_3166_2_entry
		code="BJ-DO"	name="Donga" />
	<iso_3166_2_entry
		code="BJ-KO"	name="Kouffo" />
	<iso_3166_2_entry
		code="BJ-LI"	name="Littoral" />
	<iso_3166_2_entry
		code="BJ-MO"	name="Mono" />
	<iso_3166_2_entry
		code="BJ-OU"	name="Oueme" />
	<iso_3166_2_entry
		code="BJ-PL"	name="Plateau" />
	<iso_3166_2_entry
		code="BJ-ZO"	name="Zou" />
</iso_3166_country>
	<!-- Brunei Darussalam -->
<iso_3166_country code="BN">
	<iso_3166_2_entry
		code="BN-BE"	name="Belait" />
	<iso_3166_2_entry
		code="BN-BM"	name="Brunei-Muara" />
	<iso_3166_2_entry
		code="BN-TE"	name="Temburong" />
	<iso_3166_2_entry
		code="BN-TU"	name="Tutong" />
</iso_3166_country>
	<!-- Bolivia -->
<iso_3166_country code="BO">
	<iso_3166_2_entry
		code="BO-C"	name="Cochabamba" />
	<iso_3166_2_entry
		code="BO-H"	name="Chuquisaca" />
	<iso_3166_2_entry
		code="BO-B"	name="El Beni" />
	<iso_3166_2_entry
		code="BO-L"	name="La Paz" />
	<iso_3166_2_entry
		code="BO-O"	name="Oruro" />
	<iso_3166_2_entry
		code="BO-N"	name="Pando" />
	<iso_3166_2_entry
		code="BO-P"	name="Potosi" />
	<iso_3166_2_entry
		code="BO-S"	name="Santa Cruz" />
	<iso_3166_2_entry
		code="BO-T"	name="Tarija" />
</iso_3166_country>
	<!-- Brazil -->
<iso_3166_country code="BR">
	<iso_3166_2_entry
		code="BR-AC"	name="Acre" />
	<iso_3166_2_entry
		code="BR-AL"	name="Alagoas" />
	<iso_3166_2_entry
		code="BR-AM"	name="Amazonas" />
	<iso_3166_2_entry
		code="BR-AP"	name="Amapa" />
	<iso_3166_2_entry
		code="BR-BA"	name="Bahia" />
	<iso_3166_2_entry
		code="BR-CE"	name="Ceara" />
	<iso_3166_2_entry
		code="BR-DF"	name="Distrito Federal" />
	<iso_3166_2_entry
		code="BR-ES"	name="Espirito Santo" />
	<iso_3166_2_entry
		code="BR-FN"	name="Fernando de Noronha" />
	<iso_3166_2_entry
		code="BR-GO"	name="Goias" />
	<iso_3166_2_entry
		code="BR-MA"	name="Maranhao" />
	<iso_3166_2_entry
		code="BR-MG"	name="Minas Gerais" />
	<iso_3166_2_entry
		code="BR-MS"	name="Mato Grosso do Sul" />
	<iso_3166_2_entry
		code="BR-MT"	name="Mato Grosso" />
	<iso_3166_2_entry
		code="BR-PA"	name="Para" />
	<iso_3166_2_entry
		code="BR-PB"	name="Paraiba" />
	<iso_3166_2_entry
		code="BR-PE"	name="Pernambuco" />
	<iso_3166_2_entry
		code="BR-PI"	name="Piaui" />
	<iso_3166_2_entry
		code="BR-PR"	name="Parana" />
	<iso_3166_2_entry
		code="BR-RJ"	name="Rio de Janeiro" />
	<iso_3166_2_entry
		code="BR-RN"	name="Rio Grande do Norte" />
	<iso_3166_2_entry
		code="BR-RO"	name="Rondonia" />
	<iso_3166_2_entry
		code="BR-RR"	name="Roraima" />
	<iso_3166_2_entry
		code="BR-RS"	name="Rio Grande do Sul" />
	<iso_3166_2_entry
		code="BR-SC"	name="Santa Catarina" />
	<iso_3166_2_entry
		code="BR-SE"	name="Sergipe" />
	<iso_3166_2_entry
		code="BR-SP"	name="Sao Paulo" />
	<iso_3166_2_entry
		code="BR-TO"	name="Tocatins" />
</iso_3166_country>
	<!-- Bahamas -->
<iso_3166_country code="BS">
	<iso_3166_2_entry
		code="BS-AC"	name="Acklins and Crooked Islands" />
	<iso_3166_2_entry
		code="BS-BI"	name="Bimini" />
	<iso_3166_2_entry
		code="BS-CI"	name="Cat Island" />
	<iso_3166_2_entry
		code="BS-EX"	name="Exuma" />
	<iso_3166_2_entry
		code="BS-FP"	name="Freeport" />
	<iso_3166_2_entry
		code="BS-FC"	name="Fresh Creek" />
	<iso_3166_2_entry
		code="BS-GH"	name="Governor's Harbour" />
	<iso_3166_2_entry
		code="BS-GT"	name="Green Turtle Cay" />
	<iso_3166_2_entry
		code="BS-HI"	name="Harbour Island" />
	<iso_3166_2_entry
		code="BS-HR"	name="High Rock" />
	<iso_3166_2_entry
		code="BS-IN"	name="Inagua" />
	<iso_3166_2_entry
		code="BS-KB"	name="Kemps Bay" />
	<iso_3166_2_entry
		code="BS-LI"	name="Long Island" />
	<iso_3166_2_entry
		code="BS-MH"	name="Marsh Harbour" />
	<iso_3166_2_entry
		code="BS-MG"	name="Mayaguana" />
	<iso_3166_2_entry
		code="BS-NP"	name="New Providence" />
	<iso_3166_2_entry
		code="BS-NB"	name="Nicholls Town and Berry Islands" />
	<iso_3166_2_entry
		code="BS-RI"	name="Ragged Island" />
	<iso_3166_2_entry
		code="BS-RS"	name="Rock Sound" />
	<iso_3166_2_entry
		code="BS-SP"	name="Sandy Point" />
	<iso_3166_2_entry
		code="BS-SR"	name="San Salvador and Rum Cay" />
</iso_3166_country>
	<!-- Bhutan -->
<iso_3166_country code="BT">
	<iso_3166_2_entry
		code="BT-33"	name="Bumthang" />
	<iso_3166_2_entry
		code="BT-12"	name="Chhukha" />
	<iso_3166_2_entry
		code="BT-22"	name="Dagana" />
	<iso_3166_2_entry
		code="BT-GA"	name="Gasa" />
	<iso_3166_2_entry
		code="BT-13"	name="Ha" />
	<iso_3166_2_entry
		code="BT-44"	name="Lhuentse" />
	<iso_3166_2_entry
		code="BT-42"	name="Monggar" />
	<iso_3166_2_entry
		code="BT-11"	name="Paro" />
	<iso_3166_2_entry
		code="BT-43"	name="Pemagatshel" />
	<iso_3166_2_entry
		code="BT-23"	name="Punakha" />
	<iso_3166_2_entry
		code="BT-45"	name="Samdrup Jongkha" />
	<iso_3166_2_entry
		code="BT-14"	name="Samtee" />
	<iso_3166_2_entry
		code="BT-31"	name="Sarpang" />
	<iso_3166_2_entry
		code="BT-15"	name="Thimphu" />
	<iso_3166_2_entry
		code="BT-41"	name="Trashigang" />
	<iso_3166_2_entry
		code="BT-TY"	name="Trashi Yangtse" />
	<iso_3166_2_entry
		code="BT-32"	name="Trongsa" />
	<iso_3166_2_entry